# Generated by Django 5.0.6 on 2024-06-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cv2_interface", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Image Name")),
                ("upload_image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
